In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../DataSets/exoplanetas_nasa.csv')

In [4]:
df.head()

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,...,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec
0,3.10209,K2-178 b,b,2.146336,K2-178,NaN,NaN,TIC 26078330,2018-03,2018,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,3.19225,HD 74698 c,c,2.578884,HD 74698,HD 74698,HIP 42532,TIC 308087983,2023-06,2023,...,0,86.400,NaN,NaN,0.0,NaN,86.400,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
2,3.12241,KMT-2016-BLG-1397L b,b,2.103944,KMT-2016-BLG-1397L,NaN,NaN,NaN,2018-11,2018,...,0,0.773,NaN,NaN,0.0,NaN,0.773,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
3,3.12499,GJ 1061 b,b,2.101264,GJ 1061,NaN,NaN,TIC 79611981,2020-03,2020,...,0,5.720,NaN,NaN,0.0,NaN,5.720,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
4,3.25270,Kepler-102 b,b,2.627800,Kepler-102,NaN,NaN,TIC 123357864,2014-02,2014,...,0,0.512,NaN,NaN,0.0,NaN,0.512,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6028 entries, 0 to 6027
Columns: 683 entries, objectid to pl_ndispec
dtypes: float64(496), int64(28), object(159)
memory usage: 31.4+ MB

In [6]:
def info_df(df):
    return pd.DataFrame({
    'Columna': df.columns,
    'No Nulos': df.notnull().sum().values,
    'Nulos': df.isnull().sum().values,
    'Tipo Python': df.dtypes.values,
    'Núm. valores': [len(df[col].unique()) for col in df.columns]
     })
info = info_df(df)
info

               Columna  No Nulos  Nulos Tipo Python  Núm. valores
0             objectid      6028      0     float64          5689
1              pl_name      6028      0      object          6028
2            pl_letter      6028      0      object             8
3               hostid      6028      0     float64          4487
4             hostname      6028      0      object          4500
..                 ...       ...    ...         ...           ...
678    pl_angsepformat         0   6028     float64             1
679       pl_angsepstr      5698    330     float64          2337
680    pl_angsepsymerr         0   6028     float64             1
681  pl_angsep_reflink      5698    330      object             2
682         pl_ndispec      6028      0       int64             6

[683 rows x 5 columns]

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
objectid,6028.0,3.262228e+00,0.213410,3.100000,3.122038e+00,3.178250e+00,3.317825e+00,3.999000
hostid,6028.0,2.438338e+00,0.178135,2.100330,2.326685e+00,2.508701e+00,2.572240e+00,2.999700
disc_year,6028.0,2.016815e+03,4.871597,1992.000000,2.014000e+03,2.016000e+03,2.021000e+03,2025.000000
ra,6028.0,2.336466e+02,91.340697,0.185606,1.750972e+02,2.851323e+02,2.932817e+02,359.974984
raerr1,5763.0,2.566128e-07,0.000005,0.000000,5.160389e-09,6.886861e-09,1.088200e-08,0.000163
...,...,...,...,...,...,...,...,...
pl_angseplim,5698.0,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
pl_angsepformat,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pl_angsepstr,5698.0,4.704641e+02,14026.973729,0.003530,1.140000e-01,2.760000e-01,1.350000e+00,689000.000000
pl_angsepsymerr,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pl_ndispec,6028.0,8.626410e-03,0.186464,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,6.000000

In [ ]:
df[df['pl_name'] == 'Kepler-181 c']

0       False
1       False
2       False
3       False
4       False
        ...
6023    False
6024    False
6025    False
6026    False
6027    False
Name: pl_name, Length: 6028, dtype: bool